# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: fivetooldev-development
  host: localhost
  user: geoff
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: fivetooldev-test
  host: localhost
  user: geoff
  pool: 5
  timeout: 5000

cucumber:
  <<: *test