development: &default
  adapter: postgresql
  database: fivetooldev-development
  host: localhost
  user: geoff
  pool: 5
  timeout: 5000

test: &default
  database: fivetooldev-test

cucumber:
  <<: *test

production:
  <<: *default