development: &default
  adapter: postgresql
  database: fivetooldev-development
  user: geoff
  pool: 5
  timeout: 5000
  host: localhost
  min_messages: warning

test:
  <<: *default
  database: fivetooldev-test
  min_messages: error